// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": ["http"],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
                "/winners":{
                    "post":{
                        "summary": "Add event winner",
                        "tags": ["Winners"],
                        "consumes":["application/json"],
                        "produces":["application/jsoon"],
                        "parameters": [
                            {
                                "name":"eventId",
                                "in":"query",
                                "type": "string",
                                "required": true
                            }
                        ],
                        "responses": {
                            "201":{
                                "description": "ok",
                                "schema":{
                                    "type":"string",
                                    "example":"winners info added successfully"
                                },
                            "404":{
                                "description":"Method not allowed",
                                "schema":{
                                    "type":"string",
                                    "example":"invalid input"
                                    }
                                }
                            }
                        }
                    },
                    "get": {
                        "summary":"Get Event Winners by event Id",
                        "tags": ["Winners"],
                        "consumes":["application/json"],
                        "produces":["application/jsoon"],
                        "parameters": [
                            {
                                "description": "Enter Event Id",
                                "name": "eventId",
                                "in": "query",
                                "type":"string",
                                "required": true
                            }
                        ],
                        "responses": {
                            "200":{
                                "description": "Status OK",
                                "schema":{
                                    "type":"array"
                                }
                            }
                        }
                    }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Lottery Generator API's",
	Description:      "Lottery Project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
